<?php
$previousClass = '';
$nextClass = '';
$previousPageUrl = '#';
$nextPageUrl = '#';
$pageNoArray = array_keys(array_fill(1, $this->noOfPages, ''));
$pageNoArrayForPagination = $pageNoArray;

if ($this->currentPage == 1) {
    $previousClass .= ' disabled';
}
if ($this->currentPage == $this->noOfPages || $this->noOfPages<=1 ) {
    $nextClass .= ' disabled';
}

if ($this->noOfPages > 1) {
    if ($this->currentPage > 1) {
        $previousPageUrl = $this->url($this->pageRoute, ['action' => $this->action, $this->pageKeyInRoute => $this->currentPage - 1], ['query' => $this->query]);
    }
    if ($this->currentPage < $this->noOfPages) {
        $nextPageUrl = $this->url($this->pageRoute, ['action' => $this->action, $this->pageKeyInRoute => $this->currentPage + 1], ['query' => $this->query]);
    }
}

if ($this->noOfPages > 10) {
    $pageNoArrayForPagination = [];
    for ($i = 1; $i <= $this->noOfPages; $i++) {
        if ($i <= 3 || ($i >= $this->currentPage - 1 && $i <= $this->currentPage + 1) || ($i >= $this->noOfPages - 3)) {
            $pageNoArrayForPagination[] = $i;
        }
        if ($i > 3 && $i < $this->currentPage - 1) {
            $pageNoArrayForPagination[] = '..';
            $i = $this->currentPage - 2;
        }
        if ($i > $this->currentPage + 1 && $i < $this->noOfPages - 3) {
            $pageNoArrayForPagination[] = '..';
            $i = $this->noOfPages - 3;
        }
    }
}
?>
<nav aria-label="Page navigation">
    <ul class="pagination">
        <li class="page-item <?= $previousClass ?>">
            <a class="page-link" href="<?= $previousPageUrl ?>">Previous</a>
        </li>
        <?php foreach ($pageNoArrayForPagination as $i): ?>
            <li class="page-item <?= $this->currentPage == $i || $i == '..' ? ' disabled' : '' ?>">
                <a class="page-link" href="<?= $this->currentPage == $i ? '#' : $this->url($this->pageRoute, ['action' => $this->action, $this->pageKeyInRoute => $i], ['query' => $this->query]) ?>">
                    <?= $i ?>
                </a>
            </li>
        <?php endforeach; ?>
        <li class="page-item <?= $nextClass ?>">
            <a class="page-link" href="<?= $nextPageUrl ?>">Next</a>
        </li>
        <li>
            <select class="form-control" onchange="location = this.value;" title="Go to page">
                <?php foreach ($pageNoArray as $i): ?>
                    <option <?= $i == $this->currentPage ? 'selected="selected"' : '' ?> value="<?= $this->url($this->pageRoute, ['action' => $this->action, $this->pageKeyInRoute => $i], ['query' => $this->query]) ?>" >
                        <?= $i ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </li>
        <li>&nbsp;</li>
        <li class="page-item disabled">
            <a class="page-link" href="">
                Total Record(s) : <?= $this->totalRecordCount ?>
            </a>

        </li>
    </ul>

</nav>
